version: '3.8'

services:
  flutter-web¿:
    image: flutter-web-service:latest
    container_name: flutter-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped